/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medievil2;


import java.util.Vector;
import javax.swing.*;
import medievil2.Mago;
import medievil2.Guerrero;
import medievil2.Personaje;
import medievil2.Princesa;
import medievil2.Jugador;
/**
 *
 * @author 22437
 */
public class MenuJuego extends javax.swing.JFrame {
    //public static String Jugador[];
   // public static Jugador[] vectorJugador = new Jugador[3];
   /* public static String Personaje[];
    public static Personaje[] vectorPersonaje = new Personaje[2];*/
    public static String ctePrincesa = "Princesa";
    public static String cteMago = "Mago";
    public static String cteGuerrero = "Guerrero";
    public static int Dim[];
    public static Dimension[] vectorDimension = new Dimension[12];
    public static int Time[];
    public static TiempoBean[] vectorTiempo = new TiempoBean[2];
    
    /**
     * Creates new form MenuJuego
     */
    public MenuJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblJ1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblOrden1 = new javax.swing.JLabel();
        lblPrimero1 = new javax.swing.JLabel();
        lblSegundo1 = new javax.swing.JLabel();
        lblTercero1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        comboPrimero1 = new javax.swing.JComboBox();
        comboSegundo1 = new javax.swing.JComboBox();
        comboTercero1 = new javax.swing.JComboBox();
        lblJ2 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblOrden2 = new javax.swing.JLabel();
        lblPrimero2 = new javax.swing.JLabel();
        lblSegundo2 = new javax.swing.JLabel();
        lblTercero2 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        comboPrimero2 = new javax.swing.JComboBox();
        comboSegundo2 = new javax.swing.JComboBox();
        comboTercero2 = new javax.swing.JComboBox();
        lblTiempo = new javax.swing.JLabel();
        lblDimensiones = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        comboMin = new javax.swing.JComboBox();
        comboSeg = new javax.swing.JComboBox();
        comboDim = new javax.swing.JComboBox();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJ1.setText("Jugador 1");

        lblNombre1.setText("Nombre Jugador 1");

        lblOrden1.setText("Elija orden de los personajes:");

        lblPrimero1.setText("Primero");

        lblSegundo1.setText("Segundo");

        lblTercero1.setText("Tercero");

        txtNombre1.setText("J1");
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        comboPrimero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Princesa", "Guerrero", "Mago" }));

        comboSegundo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guerrero", "Mago", "Princesa" }));
        comboSegundo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSegundo1ActionPerformed(evt);
            }
        });

        comboTercero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mago", "Princesa", "Guerrero" }));

        lblJ2.setText("Jugador 2");

        lblNombre2.setText("Nombre Jugador 2");

        lblOrden2.setText("Elija orden de los personajes");

        lblPrimero2.setText("Primero");

        lblSegundo2.setText("Segundo");

        lblTercero2.setText("Tercero");

        txtNombre2.setText("J2");
        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });

        comboPrimero2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Princesa", "Guerrero", "Mago" }));

        comboSegundo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guerrero", "Mago", "Princesa" }));

        comboTercero2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mago", "Princesa", "Guerrero" }));
        comboTercero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTercero2ActionPerformed(evt);
            }
        });

        lblTiempo.setText("Tiempo");

        lblDimensiones.setText("Dimensiones del Tablero");

        btnJugar.setText("JUGAR");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        comboMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboSeg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        comboDim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJ1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrden1)
                                    .addComponent(lblNombre1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboPrimero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPrimero1))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSegundo1)
                                            .addComponent(comboSegundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboTercero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTercero1)
                                    .addComponent(lblTercero2)
                                    .addComponent(comboTercero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtNombre1)))))
                    .addComponent(lblJ2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrden2)
                                    .addComponent(lblNombre2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDimensiones)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboDim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                                .addComponent(btnJugar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTiempo)
                                .addGap(18, 18, 18)
                                .addComponent(comboMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrimero2)
                            .addComponent(comboPrimero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSegundo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSegundo2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOrden1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimero1)
                    .addComponent(lblSegundo1)
                    .addComponent(lblTercero1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPrimero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSegundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTercero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lblJ2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre2)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOrden2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSegundo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTercero2)
                                .addComponent(lblPrimero2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboPrimero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSegundo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTercero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTiempo)
                            .addComponent(comboMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDimensiones)
                            .addComponent(comboDim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnJugar)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed
    public void ingresarDimension(){
        txtDim = new JTextField();
        txtDim.setText(comboDim.getSelectedItem().toString());
        Dimension dimen = new Dimension(12);
        dimen.setDim(Integer.parseInt(txtDim.getText()));
        for (int i=0;i<vectorDimension.length;i++){
            if (vectorDimension[i]==null){
                vectorDimension[i]=dimen;
                System.out.println("Dimension "+ vectorDimension[i].getDim());
                break;
            }
        }
    }
    
    public void ingresarDatos(){
        if (!txtNombre1.getText().isEmpty() && !txtNombre2.getText().isEmpty()){
            if (!comboPrimero1.getSelectedItem().toString().equals(comboSegundo1.getSelectedItem().toString()) &&
                    !comboPrimero1.getSelectedItem().toString().equals(comboTercero1.getSelectedItem().toString())&&
                    !comboTercero1.getSelectedItem().toString().equals(comboSegundo1.getSelectedItem().toString())){
                if (!comboPrimero2.getSelectedItem().toString().equals(comboSegundo2.getSelectedItem().toString()) &&
                    !comboPrimero2.getSelectedItem().toString().equals(comboTercero2.getSelectedItem().toString())&&
                    !comboTercero2.getSelectedItem().toString().equals(comboSegundo2.getSelectedItem().toString())){
                    Jugador jugador = new Jugador(txtNombre1.getText().toString(), txtNombre2.getText().toString());
                    Personaje p1j1, p2j1, p3j1, p1j2, p2j2, p3j2;
                    Vector<Personaje> listaJ1 = new Vector<>();
                    Vector<Personaje> listaJ2 = new Vector<>();
                    if(comboPrimero1.getSelectedItem().toString().equals(cteGuerrero)){
                        p1j1 = new Guerrero();
                    }else if(comboPrimero1.getSelectedItem().toString().equals(ctePrincesa)){
                        p1j1 = new Princesa();
                    }else{
                        p1j1 = new Mago();
                    }
                    listaJ1.add(p1j1);

                    if(comboSegundo1.getSelectedItem().toString().equals(cteGuerrero)){
                        p2j1 = new Guerrero();
                    }else if(comboSegundo1.getSelectedItem().toString().equals(ctePrincesa)){
                        p2j1 = new Princesa();
                    }else{
                        p2j1 = new Mago();
                    }
                    listaJ1.add(p2j1);

                    if(comboTercero1.getSelectedItem().toString().equals(cteGuerrero)){
                        p3j1 = new Guerrero();
                    }else if(comboTercero1.getSelectedItem().toString().equals(ctePrincesa)){
                        p3j1 = new Princesa();
                    }else{
                        p3j1 = new Mago();
                    }
                    listaJ1.add(p3j1);

                    if(comboPrimero2.getSelectedItem().toString().equals(cteGuerrero)){
                        p1j2 = new Guerrero();
                    }else if(comboPrimero2.getSelectedItem().toString().equals(ctePrincesa)){
                        p1j2 = new Princesa();
                    }else{
                        p1j2 = new Mago();
                    }
                    listaJ2.add(p1j2);

                    if(comboSegundo2.getSelectedItem().toString().equals(cteGuerrero)){
                        p2j2 = new Guerrero();
                    }else if(comboSegundo2.getSelectedItem().toString().equals(ctePrincesa)){
                        p2j2 = new Princesa();
                    }else{
                        p2j2 = new Mago();
                    }
                    listaJ2.add(p2j2);

                    if(comboTercero2.getSelectedItem().toString().equals(cteGuerrero)){
                        p3j2 = new Guerrero();
                    }else if(comboTercero2.getSelectedItem().toString().equals(ctePrincesa)){
                        p3j2 = new Princesa();
                    }else{
                        p3j2 = new Mago();
                    }
                    listaJ2.add(p3j2);
                    jugador.setListaJ1(listaJ1);
                    jugador.setListaJ2(listaJ2);
                    System.out.println(jugador.getListaJ2().get(0).getPersonaje());
                    System.out.println(jugador.getListaJ2().get(1).getPersonaje());
                    System.out.println(jugador.getListaJ2().get(2).getPersonaje());
                    System.out.println(jugador.getListaJ2().get(0).getPersonaje());
                    System.out.println(jugador.getListaJ2().get(1).getPersonaje());
                    System.out.println(jugador.getListaJ2().get(2).getPersonaje());
                    Tablero tab = new Tablero(Integer.parseInt(txtDim.getText()), jugador);
                    tab.setVisible(true);
                    this.dispose();
                } else{
                    JOptionPane.showMessageDialog(null, "Ingrese diferente orden de los personajes del Jugador 2");
                }
                
            }else {
                JOptionPane.showMessageDialog(null, "Ingrese diferente orden de los personajes del Jugador 1");
            }        
        }else {
            JOptionPane.showMessageDialog(null, "Ingrese los nombres");
        }
        
    
    }
    
    public void ingresarTiempo(){
        int a = Integer.parseInt(comboMin.getSelectedItem().toString());
        int b = a*60;
        int c = Integer.parseInt(comboSeg.getSelectedItem().toString()) + b;
        
        TiempoBean tim = new TiempoBean(2);
        tim.setSeg(c);
        
        for (int i=0;i<vectorTiempo.length;i++){
            if (vectorTiempo[i]==null){
                vectorTiempo[i]=tim;
                System.out.println("Tiempo "+ vectorTiempo[i].getSeg()+ " en segundos");
                break;
            }
        }
        
        
        
    
    }
    
    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        
        ingresarDimension();
        ingresarTiempo();        
        ingresarDatos();
    }//GEN-LAST:event_btnJugarActionPerformed

    private void comboTercero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTercero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTercero2ActionPerformed

    private void comboSegundo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSegundo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSegundo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JComboBox comboDim;
    private javax.swing.JComboBox comboMin;
    private javax.swing.JComboBox comboPrimero1;
    private javax.swing.JComboBox comboPrimero2;
    private javax.swing.JComboBox comboSeg;
    private javax.swing.JComboBox comboSegundo1;
    private javax.swing.JComboBox comboSegundo2;
    private javax.swing.JComboBox comboTercero1;
    private javax.swing.JComboBox comboTercero2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDimensiones;
    private javax.swing.JLabel lblJ1;
    private javax.swing.JLabel lblJ2;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblOrden1;
    private javax.swing.JLabel lblOrden2;
    private javax.swing.JLabel lblPrimero1;
    private javax.swing.JLabel lblPrimero2;
    private javax.swing.JLabel lblSegundo1;
    private javax.swing.JLabel lblSegundo2;
    private javax.swing.JLabel lblTercero1;
    private javax.swing.JLabel lblTercero2;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTextField txtPersonaje1J1;
    private javax.swing.JTextField txtPersonaje2J1;
    private javax.swing.JTextField txtPersonaje3J1;
    private javax.swing.JTextField txtPersonaje1J2;
    private javax.swing.JTextField txtPersonaje2J2;
    private javax.swing.JTextField txtPersonaje3J2;
    private JTextField txtDim;
    private JTextField txtMin;
    private JTextField txtSeg;
    private JTextField txtTotal;
    
    
}
