/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author 22437
 */
public class Ventana extends javax.swing.JFrame {
    private int numAviones, numEstaciones, turno = 0, val = 1, contador, pasajeros, 
            desabordajes,mantenimientos, maletas, docs;  
    private ManejadorAvion avion;
    private ManejadorPasajero pasajero;
    private ManejadorMaleta maleta;
    private ColaAvion colaAvion;
    private ManejadorMantenimiento mantenimiento;
    private String tamanio;
    private int contadorMaletas,numeroMaleta=1;
    boolean init = false;
    int validar;
    

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        area.setEditable(false);
        area.setBackground(Color.green);
        
        
    }
    public void inicio(){
        //int x = (int)(Math.random()*3+1);
        Random numGen = new Random();
        int numAl = 1+numGen.nextInt(3);
        switch (numAl){
            case 1 :
                tamanio = "Pequenio";
			desabordajes = 1;
			pasajeros = 5 + numGen.nextInt(10);
			mantenimientos = 1+numGen.nextInt(3);
                        
                break;
            case 2 :
                tamanio = "Mediano";
			desabordajes = 2;
			pasajeros = 15+numGen.nextInt(25);
			mantenimientos =  2+numGen.nextInt(4);
                break;
            case 3 :
			tamanio ="Grande";
			desabordajes=3;
			pasajeros = 30+numGen.nextInt(40);
			mantenimientos =  3+numGen.nextInt(6);
                break;
                default:
                    break;
        }
        System.out.println("Desabordaje "+desabordajes);
        System.out.println("Pasajeros "+pasajeros);
        System.out.println("Manteni "+mantenimientos);
        
    }
    public void addAvion(){
        if (numAviones>0){
            inicio();
            //String tipoAvion, int pasajero, int turnoMantenimiento, int turnoDesabordaje, int numeroAvion
                        //tipoAvion, pasajero, turnoMantenimiento, turnoDesabordaje, numeroAvion
            avion.insertarAvion(tamanio, pasajeros, mantenimientos, desabordajes, val);
            val++;
            numAviones--;
            addPasajero();
            addMaletas();
            
        
        }
    }
    public void addEstacion(){
        while(numEstaciones!=0) {
			mantenimiento.inicio();
                        //mantenimiento.inicio();
			numEstaciones--;
		}
    }
    public void pasajero(){
        int x =5;
		while(x!=0) {					
			maleta.eliminar(pasajero.cantidadMaletas());
			pasajero.eliminarPasajero();
			x--;
		}				
    
    }
    public void determinarDoc() {
		maletas = (int)(Math.random()*4+1);
		docs = (int)(Math.random()*10+1);		
	}
    public void addPasajero(){
        contador += pasajeros;
        for (int i = (contador- pasajeros+1); i < (contador+1) ; i++) {
			determinarDoc();
			pasajero.setPasajero(i, maletas, docs);
			contadorMaletas+=maletas;
		}	
        
    
    }
    public void addMaletas(){
    while(contadorMaletas!=0) {
			maleta.setMaleta(numeroMaleta);
			numeroMaleta++;
			contadorMaletas--;
		}
    
    
    }
    public void imprimir() {
		area.append("---------------- Turno " + turno + "---------------\n");
		area.append("----------- Aviones -----------\n");
		avion.imprimir(area);
		area.append("----------- Pasajero -----------\n");
		pasajero.imprimir(area);
		area.append("---------Equipaje---------\n");
		maleta.imprimir(area);
		area.append("\n---------Estacion---------\n");
		mantenimiento.imprimir(area);
		area.append("\n---------Cola---------\n");
		avion.imprimir(area);
		area.append("\n----------------- Fin " + turno + "------------------\n");
	}

    public void comprobarVacio() {
		if(avion.estaVacio() && maleta.estaVacio() && pasajero.estaVacio() && avion.estaVacio()) {
JOptionPane.showMessageDialog(null, "La Lista esta Vacia");
		}
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jLabel1.setText("SIMULADOR");

        jLabel2.setText("Cantidad Aviones");

        jLabel3.setText("Cantidad Estaciones");

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Turno");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1)
                .addContainerGap(460, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        validar = 2;
        
        turno=0;
        val = 1;
        contador =0;
        numeroMaleta = 1;
        area.setText("");
        avion = new ManejadorAvion();
        pasajero = new ManejadorPasajero();
        maleta = new ManejadorMaleta();
        mantenimiento = new ManejadorMantenimiento();
        colaAvion = new ColaAvion();
        try {
				numAviones = Integer.parseInt(jTextField1.getText());
				numEstaciones = Integer.parseInt(jTextField2.getText());
			}
			catch(NumberFormatException ex) {
				JOptionPane.showMessageDialog(null, "Unicamente se permiten numeros","ERROR",JOptionPane.ERROR_MESSAGE);
			}
        addEstacion();
        System.out.println("HOla");
        System.out.println();
        
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //System.out.println("HOla1");
        if (validar==2){
            avion.turno();
            //System.out.println("HOla2");
            mantenimiento.turno();
            //System.out.println("HOla3");
            for (int i = 0; i < 5; i++) {
                //System.out.println("HOla4");
                                    avion.eliminarAvion(colaAvion);
                  //                  System.out.println("HOla5");
                                    mantenimiento.pasar();
                    //                System.out.println("HOla6");
                                    colaAvion.mantenimiento(mantenimiento);
                                    //colaAvion.mantenimiento(mantenimiento);

                      //              System.out.println("HOla7");
                            }
                            if(!init) {
                                    addAvion();			
                                    turno++;						
                                    imprimir();
                                    init = true;
                                    return ;
                            }			
                            pasajero();
                            addAvion();			
                            turno++;						
                            imprimir();
                            comprobarVacio();
        }else{
            JOptionPane.showMessageDialog(null, "DEBE INICIAR ANTES EL SIMULADOR");
        }   
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
